name: tqdm
summary: A fast, extensible CLI progress bar
adopt-info: tqdm
grade: stable
confinement: strict
base: core18
icon: {icon}
parts:
  tqdm:
    plugin: python
    python-version: python3
    source: {source}
    source-commit: {commit}
    parse-info: [setup.py]
apps:
  tqdm:
    command: bin/tqdm
