language: python

python:
  - "2.7"
  - "3.4"

install:
  - pip install nose flake8 coverage python-coveralls
  - pip install .

script:
  - make flake8
  - make coverage

after_success:
  - coveralls
